SERVER_IP="165.194.35.203"
SERVER_HTTP_URL="nsl3.cau.ac.kr"
SERVER_PORT="20075" 
SERVER_PORTS="20075,20076,20077,20078" 
LOCAL_IP="192.168.1.150"
# LOCAL_IP="165.194.35.238" # ethernet
STARLINK_IFACE="enx588694fda289"
# STARLINK_IFACE="eno1" # ethernet
SERVER_IFACE="enp0s31f6"

DURATION=180
# PING_INTERVAL=0.2
HTTP_INTERVAL=0.05
SS_INTERVAL=0.01
IFACE_INTERVAL=0.1
IPERF_INTERVAL=0.5

TCPCUMP_WARMUP_SEC=1
TCPDUMP_SNAPLEN=128
LOG_ROOT="./logs"
TMP_ROOT="./tmp"